function [scenario, egoVehicle] = Overseas_Hwy()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 23.2 (R2023b) and Automated Driving Toolbox 23.2 (R2023b).
% Generated on: 02-Sep-2025 11:22:31

% Construct a drivingScenario object.
scenario = drivingScenario('GeoReference', [24.844535 -80.76103 0], ...
    'VerticalAxis', 'Y');

% Add all road segments
roadCenters = [-475.65828297809 -913.33907705126 0;
    -514.51443237 -903.64532406891 0;
    -1973.2279916097 -546.40070162659 0;
    -1977.3114693152 -545.40317004933 0;
    -2096.925873428 -516.28604289562 0];
lanetypes = [laneType('Driving')
    laneType('Driving')];
laneSpecification = lanespec([1 1], 'Type', lanetypes);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Overseas Highway');

roadCenters = [175.77144113223 -712.88477077254 -0.042457582429449;
    -77.783508079387 -877.83397879691 -0.054460755983939;
    -139.46474914187 -905.84734401837 -0.039282459770618;
    -186.01384471148 -920.29126650738 -0.0089397670994913;
    -217.70365390195 -928.67613260832 0.035887270312628;
    -256.64116793347 -935.44354623067 0.093940206144453;
    -301.26965906123 -938.89869215959 0.16541618146334;
    -361.70753338805 -937.57908325946 0.24985197485353;
    -411.12706883094 -929.02623342407 0.34894045051914;
    -475.65828297809 -913.33907705126 0.46100006327435];
lanetypes = [laneType('Driving')
    laneType('Driving')];
laneSpecification = lanespec([1 1], 'Type', lanetypes);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Overseas Highway');

roadCenters = [430.7253168918 -547.01142742707 -0.038108229392407;
    175.77144113223 -712.88477077254 -0.042457582429449];
lanetypes = [laneType('Driving')
    laneType('Driving')];
laneSpecification = lanespec([1 1], 'Type', lanetypes);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Overseas Highway');

roadCenters = [-2096.925873428 -516.28604289562 0.17894806122072;
    -2201.2670740169 -489.93961562745 0.058939992048266;
    -2318.6360717215 -457.44244960329 -0.05959523022824;
    -2424.6535823395 -426.85153863256 -0.16869873938867;
    -2520.7956635653 -399.11950138609 -0.26841994855823;
    -2563.5905925953 -387.39208313978 -0.34145334632828;
    -2596.8846568206 -379.26636796856 -0.40357476310032;
    -2638.5486890054 -374.40670384403 -0.46196538683233;
    -2690.0888393493 -373.04533910113 -0.51742998505543;
    -2738.1632744372 -378.31962567818 -0.56465355076307;
    -2782.5691114966 -386.31944101433 -0.60324663374666;
    -2824.5095384864 -398.60643840846 -0.63377324355079;
    -3154.7361835123 -528.46863148948 -0.80173440667809];
lanetypes = [laneType('Driving')
    laneType('Driving')];
laneSpecification = lanespec([1 1], 'Type', lanetypes);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Overseas Highway');

roadCenters = [2021.5223196188 499.09230341711 -0.33979074238297;
    1847.9242045427 386.34773577203 -0.27929858396337;
    1765.8088929461 329.84395222983 -0.25286175657241;
    1674.9811914734 265.71858211018 -0.22536829502032];
lanetypes = [laneType('Driving')
    laneType('Driving')];
laneSpecification = lanespec([1 1], 'Type', lanetypes);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Overseas Highway');

roadCenters = [1674.9811914734 265.71858211018 -0.22536829502032;
    1500.2262972396 141.39168100881 -0.1779076884857];
lanetypes = [laneType('Driving')
    laneType('Driving')];
laneSpecification = lanespec([1 1], 'Type', lanetypes);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Overseas Highway');

roadCenters = [1500.2262972396 141.39168100881 -0.1779076884857;
    1414.4190184186 82.962198288658 -0.15728068301723;
    1335.554343692 31.014003873535 -0.13982278541016;
    855.19765211268 -284.28826036123 -0.063666799643769;
    721.33341157748 -371.45017089549 -0.051635250664702;
    589.90320461543 -451.51027806192 -0.043323932200309;
    430.7253168918 -547.01142742707 -0.038108229392407];
lanetypes = [laneType('Driving')
    laneType('Driving')];
laneSpecification = lanespec([1 1], 'Type', lanetypes);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Overseas Highway');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [2013.7 496.3 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [2013.7 496.3 0;
    1998.7 487.1 0];
speed = [30;30];
waittime = [0;0];
trajectory(egoVehicle, waypoints, speed, waittime);

% Add the non-ego actors
car1 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [1428.49702131186 93.9065333576781 -0.2], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car1');
waypoints = [1428.49702131186 93.9065333576781 -0.2;
    1167.5 -77 -0.1;
    719.2 -370 0;
    662.4 -405.2 0;
    614.2 -434.4 0;
    592 -447.8 0;
    532 -484.5 0;
    507.4 -498.7 0;
    447.8 -534.7 0;
    427.3 -546.9 0;
    413.2 -555.9 0;
    397.2 -565.8 0;
    363.7 -587.5 0;
    265.7 -651.7 0;
    212.8 -686.7 0;
    170.7 -713.4 0;
    149.1 -729.4 0;
    132 -742 0;
    103.3 -762 0;
    69.3 -786.2 0;
    14.5 -821.7 0;
    -34.9 -852.2 0;
    -85.1 -878.9 0;
    -123.9 -898.1 0;
    -162 -910.8 0;
    -205.3 -923.2 0;
    -220.6 -927.2 0;
    -243.8 -931.5 0;
    -269.2 -934.4 0;
    -297.3 -936.1 0;
    -325.1 -937.5 0;
    -354.4 -936.3 0;
    -383 -933 0;
    -426 -923.1 0;
    -526.2 -899.6 0;
    -595.4 -880.8 0;
    -804.8 -829.4 0;
    -846.9 -819.3 0;
    -1369.2 -691.1 0];
speed = [25;25;25;25;25;25;25;25;25;25;25;25;25;25;25;25;25;25;25;25;25;25;25;25;25;25;25;25;25;25;25;25;25;25;25;25;25;25;25];
waittime = [0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0];
trajectory(car1, waypoints, speed, waittime);

