function [scenario, egoVehicle] = Queen_Elizabeth_Way_Oakville()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 23.2 (R2023b) and Automated Driving Toolbox 23.2 (R2023b).
% Generated on: 04-Sep-2025 10:58:51

% Construct a drivingScenario object.
scenario = drivingScenario('GeoReference', [43.456595 -79.68902 0], ...
    'VerticalAxis', 'Y');

% Add all road segments
roadCenters = [401.93015283915 528.26715628101 0;
    122.73416021778 172.91972906122 0;
    -103.68694269802 -106.46789276204 0;
    -328.44246726081 -369.27151439757 0;
    -377.07395511351 -428.67497801743 0];
lanetypes = [laneType('Driving')
    laneType('Driving')
    laneType('Driving')
    laneType('Driving')];
laneSpecification = lanespec(4, 'Type', lanetypes);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Queen Elizabeth Way');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [398.4 527.2 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [398.4 527.2 0;
    350.6 464.7 0];
speed = [30;30];
trajectory(egoVehicle, waypoints, speed);

% Add the non-ego actors
truck = vehicle(scenario, ...
    'ClassID', 2, ...
    'Length', 8.2, ...
    'Width', 2.5, ...
    'Height', 3.5, ...
    'Position', [343.357984720435 462.664293832606 0], ...
    'RearOverhang', 1, ...
    'FrontOverhang', 0.9, ...
    'Mesh', driving.scenario.truckMesh, ...
    'Name', 'Truck');
waypoints = [343.357984720435 462.664293832606 0;
    308.6 417.5 0;
    272.4 371.9 0;
    219.6 305.3 0;
    5.3 34.9 0;
    -163.7 -167.6 0;
    -306.8 -334.5 0;
    -379.5 -422.2 0];
speed = [20;20;20;20;20;20;20;20];
trajectory(truck, waypoints, speed);

car1 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [329.1 438.7 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car1');
waypoints = [329.1 438.7 0;
    284.8 381.7 0;
    144.9 202.9 0;
    -24.6 -8.5 0;
    -172.1 -184.3 0;
    -323.5 -359.6 0;
    -378.6 -426.5 0];
speed = [25;25;25;25;25;25;25];
trajectory(car1, waypoints, speed);

car2 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [384.852348306329 516.058278878883 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car2');
waypoints = [384.852348306329 516.058278878883 0;
    366.1 491.8 0;
    350.6 471.4 0;
    323 435.8 0;
    309 407.1 0;
    287.7 372.9 0;
    251.5 329.4 0;
    -44.8 -43.9 0;
    -323.4 -370.4 0;
    -369.3 -425.3 0];
speed = [42;42;42;42;42;42;42;42;42;42];
trajectory(car2, waypoints, speed);

