function [scenario, egoVehicle] = scenarioOstacoloSuStrada()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 23.2 (R2023b) and Automated Driving Toolbox 23.2 (R2023b).
% Generated on: 08-May-2024 12:26:21

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [-39.7 0.8 0;
    400 0.1 0];
marking = [laneMarking('Solid', 'Color', [0.98 0.86 0.36])
    laneMarking('Dashed')
    laneMarking('DoubleSolid')
    laneMarking('Dashed')
    laneMarking('Solid')];
laneSpecification = lanespec(4, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-33.7 -1.2 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [-33.7 -1.2 0;
    399.43 -1.68 0.01];
speed = [30;30];
trajectory(egoVehicle, waypoints, speed);

% Add the non-ego actors
car1 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-13.4989532369351 -4.7023469619669 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car1');
waypoints = [-13.4989532369351 -4.7023469619669 0;
    399.62 -5.41 0.01];
speed = [20;20];
trajectory(car1, waypoints, speed);

car2 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [136.2 5.6 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car2');
waypoints = [136.2 5.6 0;
    -37.5 6.1 0];
speed = [30;30];
trajectory(car2, waypoints, speed);

vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [383.91 -1.65 0.01], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car3');

