function [scenario, egoVehicle] = A8_Stoccarda_Monaco()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 23.2 (R2023b) and Automated Driving Toolbox 23.2 (R2023b).
% Generated on: 01-Sep-2025 15:21:46

% Construct a drivingScenario object.
scenario = drivingScenario('GeoReference', [48.296895 11.227135 0], ...
    'VerticalAxis', 'Y');

% Add all road segments
roadCenters = [2132.5677710704 -1066.1930347743 0;
    2055.0089816141 -1019.9973937167 0;
    1952.2980237215 -962.03371829859 0;
    1787.7865643934 -873.45343100007 0;
    1615.5038424538 -786.47181212549 0;
    1367.2561092781 -673.23921974517 0;
    899.56128114364 -465.06215095486 0;
    650.91914957798 -354.38921111013 0;
    503.58769814418 -289.41004453551 0;
    375.64101308912 -233.43269700111 0;
    261.20107339131 -179.65354962645 0;
    243.11852674292 -171.15896728225 0;
    209.59507712343 -154.78111421149 0;
    119.16138373482 -110.59439677204 0;
    21.494861948604 -60.446162212641 0;
    -106.39708923848 12.477197571962 0;
    -258.93975975189 107.84388115353 0;
    -287.93402569942 128.52775072062 0];
marking = [laneMarking('Solid', 'Color', [0.98 0.86 0.36])
    laneMarking('Dashed')
    laneMarking('Dashed')
    laneMarking('DoubleSolid')
    laneMarking('Dashed')
    laneMarking('Dashed')
    laneMarking('Solid')];
laneSpecification = lanespec(6, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '28802113-477921130-477921133');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [2132.3 -1060 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [2132.3 -1060 0;
    2110.9 -1046.3 0];
speed = [30;30];
trajectory(egoVehicle, waypoints, speed);

% Add the non-ego actors
car1 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [1804.8 -876.3 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car1');
waypoints = [1804.8 -876.3 0;
    1694.4 -818.9 0;
    1262.8 -620.8 0;
    1039.2 -521.1 0;
    598.8 -325.7 0;
    394 -235.8 0;
    179.2 -134 0;
    58.8 -73.9 0;
    -11.7 -36.6 0;
    -81.5 4 0;
    -136.9 37.2 0;
    -206.8 79.2 0;
    -239.1 100.1 0;
    -283.4 131.8 0];
speed = [35;35;35;35;35;35;35;35;35;35;35;35;35;35];
trajectory(car1, waypoints, speed);

truck = vehicle(scenario, ...
    'ClassID', 2, ...
    'Length', 8.2, ...
    'Width', 2.5, ...
    'Height', 3.5, ...
    'Position', [1976.1 -964.6 0], ...
    'RearOverhang', 1, ...
    'FrontOverhang', 0.9, ...
    'Mesh', driving.scenario.truckMesh, ...
    'Name', 'Truck');
waypoints = [1976.1 -964.6 0;
    1872.6 -907.5 0;
    1830.7 -885.5 0;
    1707.5 -821 0;
    1602.7 -770 0;
    1562.2 -750.7 0;
    1408.5 -681 0;
    1341.5 -651.2 0;
    1024.2 -510.3 0;
    780.3 -402.4 0;
    498.2 -276.5 0;
    428.2 -246.7 0;
    348 -211.3 0;
    272.9 -175.5 0;
    176.6 -127.5 0;
    84.8 -82.3 0;
    17.2 -48.2 0;
    -80.8 9.9 0;
    -191.2 73.4 0];
speed = [20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20];
trajectory(truck, waypoints, speed);

