function [scenario, egoVehicle] = Las_Vegas_Freeway()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 23.2 (R2023b) and Automated Driving Toolbox 23.2 (R2023b).
% Generated on: 04-Sep-2025 12:05:20

% Construct a drivingScenario object.
scenario = drivingScenario('GeoReference', [35.8253485 -115.2948425 0], ...
    'VerticalAxis', 'Y');

% Add all road segments
roadCenters = [-2726.9066398105 -4476.4299066707 0;
    -2261.6589241444 -3696.6245902012 0;
    -1650.563528299 -2669.4918317568 0;
    -705.67935237068 -1091.9754143169 0;
    -362.33667762503 -510.38890817532 0;
    -206.08590225304 -264.22760879304 0;
    -72.931854843606 -75.771387867024 0;
    35.719882216903 60.848217175991 0;
    5688.1475782633 6104.9680669476 0];
lanetypes = [laneType('Driving')
    laneType('Driving')
    laneType('Driving')];
laneSpecification = lanespec(3, 'Type', lanetypes);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Las Vegas Freeway');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [986.435937083158 1187.5337298364 -0.2], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [986.435937083158 1187.5337298364 -0.2;
    975.5 1175.1 -0.2];
speed = [30;30];
trajectory(egoVehicle, waypoints, speed);

% Add the non-ego actors
car1 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [944.1 1138.9 -0.2], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car1');
waypoints = [944.1 1138.9 -0.2;
    897.9 1084.9 -0.1;
    870.9 1055 -0.1;
    831.9 1008.5 -0.1;
    801.3 973.7 -0.1;
    745.8 909.5 -0.1;
    705.1 862.1 -0.1;
    628.6 772.4 -0.1;
    608.5 748.2 -0.1;
    516.1 638.8 0;
    296.2 378.5 0;
    202 263.4 0];
speed = [30;30;30;25;20;20;25;25;25;30;30;30];
waittime = [0;0;0;0;0;0;0;0;0;0;0;0];
trajectory(car1, waypoints, speed, waittime);

