function [scenario, egoVehicle] = curvaLunga()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 23.2 (R2023b) and Automated Driving Toolbox 23.2 (R2023b).
% Generated on: 06-Dec-2024 15:02:16

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [0 0 0;
    0 -500 0;
    254 -984 0;
    551 -1172 0;
    850 -1191 0];
marking = [laneMarking('Solid', 'Color', [0.98 0.86 0.36])
    laneMarking('DoubleSolid')
    laneMarking('Solid')];
laneSpecification = lanespec(2, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-2.5 -2.7 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [-2.5 -2.7 0;
    -7.7 -61.9 0;
    -10.6 -94.1 0];
speed = [30;30;30];
trajectory(egoVehicle, waypoints, speed);

% Add the non-ego actors
car1 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-16.4 -183.4 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car1');
waypoints = [-16.4 -183.4 0;
    -18.9 -222.5 0;
    -19.3 -251.6 0;
    -19.8 -279.7 0;
    -19.7 -302.4 0;
    -19.3 -329.3 0;
    -18.5 -347.8 0;
    -17.3 -372 0;
    -15.6 -395.3 0;
    -13.9 -416.8 0;
    -11.8 -435.3 0;
    -7.6 -468.8 0;
    -2.2 -501 0;
    5.8 -537.7 0;
    17.4 -582.3 0;
    26.2 -611.8 0;
    37.5 -644.7 0;
    49.8 -675.6 0;
    59 -698.1 0;
    73.5 -728.6 0;
    84.7 -752.1 0;
    100 -781.3 0;
    120.1 -815.4 0;
    146.9 -856.4 0;
    160.5 -875.4 0;
    176.26 -897.04 0.01;
    182.85 -905.25 0.01;
    213.2 -942.7 0;
    232.7 -963.8 0;
    259.4 -992.8 0;
    281.7 -1014.3 0;
    305 -1035.2 0;
    333.2 -1059.3 0;
    354.6 -1076.1 0;
    379.4 -1093.6 0;
    415.7 -1116.1 0;
    451.8 -1135.7 0;
    488.9 -1152.1 0;
    510.5 -1160.6 0;
    533.4 -1168.6 0;
    558.1 -1175.1 0;
    576.6 -1179.9 0;
    606.8 -1185.6 0;
    634.7 -1189.4 0;
    649.4 -1191.5 0;
    673.2 -1193.2 0;
    695.4 -1194.7 0;
    716.6 -1195.3 0;
    737.9 -1195.7 0;
    765.9 -1195.5 0;
    794.6 -1194.6 0;
    823.2 -1193.6 0;
    847.6 -1193.1 0];
speed = [20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20];
trajectory(car1, waypoints, speed);

