function [scenario, egoVehicle] = FrenataBrusca()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 23.2 (R2023b) and Automated Driving Toolbox 23.2 (R2023b).
% Generated on: 06-Mar-2025 16:28:34

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [-250 0 0;
    250 0 0];
marking = [laneMarking('Solid', 'Color', [0.98 0.86 0.36])
    laneMarking('Solid')
    laneMarking('Solid')];
laneSpecification = lanespec(2, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-248.2 -1.9 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [-248.2 -1.9 0;
    -190 -1.7 0];
speed = [25;25];
trajectory(egoVehicle, waypoints, speed);

% Add the non-ego actors
car1 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-184.2 -2 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car1');
waypoints = [-184.2 -2 0;
    -140 -2 0;
    -100.4 -2 0;
    -74.28 -2 0;
    -60.01 -2 0;
    -48.88 -2 0;
    -42.2 -2 0;
    -38.6 -2 0;
    -29.4 -2 0;
    247.8 -2 0];
speed = [20;20;20;20;15;12;10;7;20;20];
waittime = [0;0;0;0;0;0;0;0;0;0];
trajectory(car1, waypoints, speed, waittime);

