function [scenario, egoVehicle] = Ushape()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 23.2 (R2023b) and Automated Driving Toolbox 23.2 (R2023b).
% Generated on: 27-Aug-2025 12:41:53

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [50.2 11.6 0;
    -49.4 6.1 0;
    -118.8 -24.5 0;
    -150.4 -99.8 0;
    -116.9 -177 0;
    -50 -191.1 0;
    49.5 -190.6 0];
marking = [laneMarking('Solid', 'Color', [0.98 0.86 0.36])
    laneMarking('DoubleSolid')
    laneMarking('Solid')];
laneSpecification = lanespec(2, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [45.5 13.6 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [45.5 13.6 0;
    38.7 13.5 0];
speed = [30;30];
trajectory(egoVehicle, waypoints, speed);

% Add the non-ego actors
car1 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-13.9 12.5 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car1');
waypoints = [-13.9 12.5 0;
    -40.4 9.9 0;
    -60.4 6.4 0;
    -75 2 0;
    -85.3 -1.7 0;
    -95.7 -6.6 0;
    -108.3 -13.1 0;
    -116.6 -19.8 0;
    -127.7 -30.6 0;
    -135.1 -40.8 0;
    -141.6 -53.2 0;
    -145.6 -64.1 0;
    -148.7 -76 0;
    -150.8 -88 0;
    -152.5 -100.6 0;
    -152.2 -115 0;
    -149.3 -131.4 0;
    -143.7 -148 0;
    -134.2 -163.6 0;
    -120.2 -176.7 0;
    -104.6 -185.2 0;
    -92.6 -189.2 0;
    -77.3 -191.7 0;
    -62.3 -192.6 0;
    -49 -193.6 0;
    -28.4 -193.4 0;
    47.5 -192.4 0];
speed = [14;14;14;14;14;14;14;14;14;14;14;14;14;14;14;14;14;14;14;14;14;14;14;14;14;14;14];
trajectory(car1, waypoints, speed);

